'use client';

import { useEffect, useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Settings, Store, Clock, Bell, Shield, CreditCard, Save } from "lucide-react";
import ProtectedRoute from "@/components/ProtectedRoute";
import { AdminSidebar, AdminMobileSidebar } from "@/components/admin/AdminSidebar";
import { cn } from "@/lib/utils";
import { ImageField } from "@/components/ui/image-field";
import { useAuth } from "@/contexts/AuthContext";
import { useRouter } from "next/navigation";
import { useCurrencyStore } from "@/stores/currency.store";
import { CurrencySwitcher } from "@/components/ui/currency-switcher";
import { doc, getDoc, setDoc, collection, query, where, getDocs, serverTimestamp } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { toast } from "sonner";

export default function AdminSettings() {
  const { user, logout } = useAuth();
  const router = useRouter();
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const { currency, setCurrency } = useCurrencyStore();
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [branchDocId, setBranchDocId] = useState<string | null>(null);

  const handleLogout = () => {
    logout();
    router.push('/login');
  };

  const [settings, setSettings] = useState({
    // Business Settings
    businessName: "",
    businessEmail: "",
    businessPhone: "",
    businessAddress: "",
    businessCity: "",
    businessCountry: "",
    businessWebsite: "",
    businessLogo: "",
    businessDescription: "",
    timezone: "",

    // Operating Hours
    monday: { open: "09:00", close: "22:00", closed: false },
    tuesday: { open: "09:00", close: "22:00", closed: false },
    wednesday: { open: "09:00", close: "22:00", closed: false },
    thursday: { open: "09:00", close: "22:00", closed: false },
    friday: { open: "09:00", close: "22:00", closed: false },
    saturday: { open: "09:00", close: "22:00", closed: false },
    sunday: { open: "09:00", close: "22:00", closed: false },

    // Notifications
    emailNotifications: true,
    smsNotifications: false,
    bookingReminders: true,
    marketingEmails: false,

    // Booking Settings
    advanceBookingDays: 30,
    cancellationHours: 24,
    autoConfirmBookings: false,
    requireDeposit: false,
    depositAmount: 0,

    // Payment Settings
    acceptCash: true,
    acceptCard: true,
    acceptCheck: true,
    acceptDigital: true,
    acceptEwallet: true,
    taxRate: 5,

    // Calendar Display Settings
    calendarDisplaySettings: {
      timeSlotGap: 30,
      layoutMode: 'time-top' as 'time-top' | 'employee-top',
      businessHours: { start: 9, end: 22 },
      hiddenHours: [] as number[],
      totalValueDisplayMode: 'both' as 'both' | 'with-tax' | 'without-tax',
      invoiceValueDisplayMode: 'with-tax' as 'with-tax' | 'without-tax',
    },

    // Invoice Disclaimer Settings
    invoiceDisclaimerTemplate:
      'This invoice is generated by system with current date and time: {{dateTime}}. No refund available on any service, product, or e-wallet transaction.'
  });

  useEffect(() => {
    if (!user) return;
    loadSettingsFromFirebase();
  }, [user]);

  const normalizeDayTiming = (
    value: any,
    fallback: { open: string; close: string; closed: boolean }
  ) => {
    const source = value || {};
    return {
      open: String(source.open ?? source.opening ?? fallback.open),
      close: String(source.close ?? source.closing ?? fallback.close),
      closed: Boolean(source.closed ?? fallback.closed),
    };
  };

  const resolveBranchDocId = async (): Promise<string | null> => {
    if (user?.branchId) return user.branchId;
    if (!user?.branchName) return null;

    const branchesRef = collection(db, 'branches');
    const branchQuery = query(branchesRef, where('name', '==', user.branchName));
    const snapshot = await getDocs(branchQuery);
    if (!snapshot.empty) return snapshot.docs[0].id;

    // Fallback: tolerant match by normalized branch name when exact query misses.
    const allBranchesSnap = await getDocs(branchesRef);
    const normalizedTarget = String(user.branchName || '').trim().toLowerCase();
    const tolerantMatch = allBranchesSnap.docs.find((branchDoc) =>
      String(branchDoc.data().name || '').trim().toLowerCase() === normalizedTarget
    );

    return tolerantMatch?.id || null;
  };

  const loadSettingsFromFirebase = async () => {
    try {
      setLoading(true);
      const resolvedId = await resolveBranchDocId();
      if (!resolvedId) {
        toast.error('Branch not linked to this admin. Please assign a branch.');
        return;
      }

      setBranchDocId(resolvedId);
      const branchRef = doc(db, 'branches', resolvedId);
      const branchSnap = await getDoc(branchRef);

      if (branchSnap.exists()) {
        const data = branchSnap.data();
        const weekly = data.weeklyTimings || {};

        setSettings((prev) => ({
          ...prev,
          businessName: data.name || prev.businessName,
          businessEmail: data.email || prev.businessEmail,
          businessPhone: data.phone || prev.businessPhone,
          businessAddress: data.address || prev.businessAddress,
          businessCity: data.city || prev.businessCity,
          businessCountry: data.country || prev.businessCountry,
          businessWebsite: data.website || prev.businessWebsite,
          businessLogo: data.image || data.businessLogo || prev.businessLogo,
          businessDescription: data.description || prev.businessDescription,
          timezone: data.timezone || prev.timezone,
          emailNotifications: data.emailNotifications ?? prev.emailNotifications,
          smsNotifications: data.smsNotifications ?? prev.smsNotifications,
          bookingReminders: data.bookingReminders ?? prev.bookingReminders,
          marketingEmails: data.marketingEmails ?? prev.marketingEmails,
          advanceBookingDays: Number.isFinite(Number(data.advanceBookingDays))
            ? Number(data.advanceBookingDays)
            : prev.advanceBookingDays,
          cancellationHours: Number.isFinite(Number(data.cancellationHours))
            ? Number(data.cancellationHours)
            : prev.cancellationHours,
          autoConfirmBookings: data.autoConfirmBookings ?? prev.autoConfirmBookings,
          requireDeposit: data.requireDeposit ?? prev.requireDeposit,
          depositAmount: Number.isFinite(Number(data.depositAmount))
            ? Number(data.depositAmount)
            : prev.depositAmount,
          acceptCash: data.acceptCash ?? prev.acceptCash,
          acceptCard: data.acceptCard ?? prev.acceptCard,
          acceptCheck: data.acceptCheck ?? prev.acceptCheck,
          acceptDigital: data.acceptDigital ?? prev.acceptDigital,
          acceptEwallet: data.acceptEwallet ?? prev.acceptEwallet,
          taxRate: Number.isFinite(Number(data.taxRate)) ? Number(data.taxRate) : prev.taxRate,
          monday: normalizeDayTiming(weekly.monday, prev.monday),
          tuesday: normalizeDayTiming(weekly.tuesday, prev.tuesday),
          wednesday: normalizeDayTiming(weekly.wednesday, prev.wednesday),
          thursday: normalizeDayTiming(weekly.thursday, prev.thursday),
          friday: normalizeDayTiming(weekly.friday, prev.friday),
          saturday: normalizeDayTiming(weekly.saturday, prev.saturday),
          sunday: normalizeDayTiming(weekly.sunday, prev.sunday),
          calendarDisplaySettings: {
            ...prev.calendarDisplaySettings,
            ...(data.calendarDisplaySettings || {}),
            businessHours: {
              ...prev.calendarDisplaySettings.businessHours,
              ...(data.calendarDisplaySettings?.businessHours || {}),
            },
            hiddenHours: Array.isArray(data.calendarDisplaySettings?.hiddenHours)
              ? data.calendarDisplaySettings.hiddenHours
              : prev.calendarDisplaySettings.hiddenHours,
          },
          invoiceDisclaimerTemplate:
            typeof data.invoiceDisclaimerTemplate === 'string' && data.invoiceDisclaimerTemplate.trim().length > 0
              ? data.invoiceDisclaimerTemplate
              : prev.invoiceDisclaimerTemplate,
        }));

        toast.success('Branch settings loaded from Firebase.');
      } else {
        toast.info('No branch settings found. Using defaults.');
      }
    } catch (error) {
      console.error('Error loading branch settings:', error);
      toast.error('Failed to load branch settings from Firebase.');
    } finally {
      setLoading(false);
    }
  };

  const handleSettingChange = (key: string, value: any) => {
    setSettings(prev => ({
      ...prev,
      [key]: value
    }));
  };

  const handleOperatingHoursChange = (day: string, field: string, value: string | boolean) => {
    setSettings(prev => ({
      ...prev,
      [day]: {
        ...prev[day as keyof typeof prev] as any,
        [field]: value
      }
    }));
  };

  const handleCalendarDisplaySettingChange = (
    key: 'timeSlotGap' | 'layoutMode' | 'businessHours' | 'hiddenHours' | 'totalValueDisplayMode' | 'invoiceValueDisplayMode',
    value: any
  ) => {
    setSettings((prev) => ({
      ...prev,
      calendarDisplaySettings: {
        ...prev.calendarDisplaySettings,
        [key]: value,
      },
    }));
  };

  const handleSave = async () => {
    try {
      if (!branchDocId) {
        toast.error('Branch not linked to this admin. Please assign a branch.');
        return;
      }

      setSaving(true);
      const branchRef = doc(db, 'branches', branchDocId);

      await setDoc(
        branchRef,
        {
          name: settings.businessName,
          email: settings.businessEmail,
          phone: settings.businessPhone,
          address: settings.businessAddress,
          city: settings.businessCity,
          country: settings.businessCountry,
          website: settings.businessWebsite,
          image: settings.businessLogo,
          businessLogo: settings.businessLogo,
          description: settings.businessDescription,
          timezone: settings.timezone,
          openingTime: settings.monday.open,
          closingTime: settings.monday.close,
          weeklyTimings: {
            monday: { open: settings.monday.open, close: settings.monday.close, opening: settings.monday.open, closing: settings.monday.close, closed: settings.monday.closed },
            tuesday: { open: settings.tuesday.open, close: settings.tuesday.close, opening: settings.tuesday.open, closing: settings.tuesday.close, closed: settings.tuesday.closed },
            wednesday: { open: settings.wednesday.open, close: settings.wednesday.close, opening: settings.wednesday.open, closing: settings.wednesday.close, closed: settings.wednesday.closed },
            thursday: { open: settings.thursday.open, close: settings.thursday.close, opening: settings.thursday.open, closing: settings.thursday.close, closed: settings.thursday.closed },
            friday: { open: settings.friday.open, close: settings.friday.close, opening: settings.friday.open, closing: settings.friday.close, closed: settings.friday.closed },
            saturday: { open: settings.saturday.open, close: settings.saturday.close, opening: settings.saturday.open, closing: settings.saturday.close, closed: settings.saturday.closed },
            sunday: { open: settings.sunday.open, close: settings.sunday.close, opening: settings.sunday.open, closing: settings.sunday.close, closed: settings.sunday.closed },
          },
          calendarDisplaySettings: settings.calendarDisplaySettings,
          emailNotifications: settings.emailNotifications,
          smsNotifications: settings.smsNotifications,
          bookingReminders: settings.bookingReminders,
          marketingEmails: settings.marketingEmails,
          advanceBookingDays: settings.advanceBookingDays,
          cancellationHours: settings.cancellationHours,
          autoConfirmBookings: settings.autoConfirmBookings,
          requireDeposit: settings.requireDeposit,
          depositAmount: settings.depositAmount,
          acceptCash: settings.acceptCash,
          acceptCard: settings.acceptCard,
          acceptCheck: settings.acceptCheck,
          acceptDigital: settings.acceptDigital,
          acceptEwallet: settings.acceptEwallet,
          taxRate: settings.taxRate,
          invoiceDisclaimerTemplate: settings.invoiceDisclaimerTemplate,
          updatedAt: serverTimestamp(),
        },
        { merge: true }
      );

      toast.success('Branch settings saved to Firebase.');
    } catch (error) {
      console.error('Error saving branch settings:', error);
      toast.error('Failed to save branch settings.');
    } finally {
      setSaving(false);
    }
  };

  const daysOfWeek = [
    { key: 'monday', label: 'Monday' },
    { key: 'tuesday', label: 'Tuesday' },
    { key: 'wednesday', label: 'Wednesday' },
    { key: 'thursday', label: 'Thursday' },
    { key: 'friday', label: 'Friday' },
    { key: 'saturday', label: 'Saturday' },
    { key: 'sunday', label: 'Sunday' }
  ];

  return (
    <ProtectedRoute requiredRole="admin">
      <div className="flex h-screen bg-gray-50">
        {/* Sidebar */}
        <AdminSidebar role={user?.role === 'super_admin' ? 'super_admin' : 'branch_admin'} onLogout={handleLogout}
          isOpen={sidebarOpen}
          onToggle={() => setSidebarOpen(!sidebarOpen)}
          allowedPages={user?.allowedPages || []} />

        {/* Main Content */}
        <div className={cn(
          "flex-1 flex flex-col transition-all duration-300 ease-in-out",
          sidebarOpen ? "lg:ml-0" : "lg:ml-0"
        )}>
          {/* Header */}
          <header className="bg-white shadow-sm border-b">
            <div className="flex items-center justify-between px-4 py-4 lg:px-8">
              <div className="flex items-center gap-4">
                <AdminMobileSidebar role={user?.role === 'super_admin' ? 'super_admin' : 'branch_admin'} onLogout={handleLogout}
          isOpen={sidebarOpen}
          onToggle={() => setSidebarOpen(!sidebarOpen)}
          allowedPages={user?.allowedPages || []} />
                <div>
                  <h1 className="text-2xl font-bold text-gray-900">Settings</h1>
                  <p className="text-sm text-gray-600">Manage your business settings</p>
                </div>
              </div>
              <div className="flex items-center gap-4">
                <CurrencySwitcher />
                <Button onClick={handleSave} className="bg-secondary hover:bg-secondary/90" disabled={saving}>
                  <Save className="w-4 h-4 mr-2" />
                  {saving ? 'Saving...' : 'Save Changes'}
                </Button>
                <span className="text-sm text-gray-600 hidden sm:block">Welcome, {user?.email}</span>
                <Button variant="outline" onClick={handleLogout} className="hidden sm:flex">
                  Logout
                </Button>
              </div>
            </div>
          </header>

          {/* Content */}
          <div className="flex-1 overflow-auto">
            <div className="p-4 lg:p-8">
              <Tabs defaultValue="business" className="space-y-6">
                <TabsList className="grid w-full grid-cols-5">
                  <TabsTrigger value="business" className="flex items-center gap-2">
                    <Store className="w-4 h-4" />
                    Business
                  </TabsTrigger>
                  <TabsTrigger value="hours" className="flex items-center gap-2">
                    <Clock className="w-4 h-4" />
                    Hours
                  </TabsTrigger>
                  <TabsTrigger value="notifications" className="flex items-center gap-2">
                    <Bell className="w-4 h-4" />
                    Notifications
                  </TabsTrigger>
                  <TabsTrigger value="booking" className="flex items-center gap-2">
                    <Settings className="w-4 h-4" />
                    Booking
                  </TabsTrigger>
                  <TabsTrigger value="payment" className="flex items-center gap-2">
                    <CreditCard className="w-4 h-4" />
                    Payment
                  </TabsTrigger>
                </TabsList>

                {/* Business Settings */}
                <TabsContent value="business">
                  <Card>
                    <CardHeader>
                      <CardTitle>Business Information</CardTitle>
                      <CardDescription>Update your business details and profile</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div className="space-y-2">
                          <Label htmlFor="businessName">Business Name</Label>
                          <Input
                            id="businessName"
                            value={settings.businessName}
                            onChange={(e) => handleSettingChange('businessName', e.target.value)}
                          />
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="businessEmail">Business Email</Label>
                          <Input
                            id="businessEmail"
                            type="email"
                            value={settings.businessEmail}
                            onChange={(e) => handleSettingChange('businessEmail', e.target.value)}
                          />
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="businessPhone">Business Phone</Label>
                          <Input
                            id="businessPhone"
                            value={settings.businessPhone}
                            onChange={(e) => handleSettingChange('businessPhone', e.target.value)}
                          />
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="businessWebsite">Business Website</Label>
                          <Input
                            id="businessWebsite"
                            value={settings.businessWebsite}
                            onChange={(e) => handleSettingChange('businessWebsite', e.target.value)}
                            placeholder="https://example.com"
                          />
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="businessCity">City</Label>
                          <Input
                            id="businessCity"
                            value={settings.businessCity}
                            onChange={(e) => handleSettingChange('businessCity', e.target.value)}
                          />
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="businessCountry">Country</Label>
                          <Input
                            id="businessCountry"
                            value={settings.businessCountry}
                            onChange={(e) => handleSettingChange('businessCountry', e.target.value)}
                          />
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="timezone">Timezone</Label>
                          <Select value={settings.timezone} onValueChange={(value) => handleSettingChange('timezone', value)}>
                            <SelectTrigger>
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="America/New_York">Eastern Time</SelectItem>
                              <SelectItem value="America/Chicago">Central Time</SelectItem>
                              <SelectItem value="America/Denver">Mountain Time</SelectItem>
                              <SelectItem value="America/Los_Angeles">Pacific Time</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="businessAddress">Business Address</Label>
                        <Textarea
                          id="businessAddress"
                          value={settings.businessAddress}
                          onChange={(e) => handleSettingChange('businessAddress', e.target.value)}
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="businessDescription">Business Description</Label>
                        <Textarea
                          id="businessDescription"
                          value={settings.businessDescription}
                          onChange={(e) => handleSettingChange('businessDescription', e.target.value)}
                          rows={3}
                        />
                      </div>
                      <div className="space-y-2">
                        <Label>Business Logo</Label>
                        <ImageField
                          label=""
                          value={settings.businessLogo}
                          onChange={(url) => handleSettingChange('businessLogo', url)}
                          folder="images/branches"
                          placeholder="https://example.com/branch-logo.png"
                          inputId="businessLogo"
                        />
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>

                {/* Operating Hours */}
                <TabsContent value="hours">
                  <Card>
                    <CardHeader>
                      <CardTitle>Operating Hours</CardTitle>
                      <CardDescription>Set your business hours for each day</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-4">
                        {daysOfWeek.map((day) => (
                          <div key={day.key} className="flex items-center gap-4 p-4 border rounded-lg">
                            <div className="w-24">
                              <Label className="text-sm font-medium">{day.label}</Label>
                            </div>
                            <div className="flex items-center gap-2">
                              <Switch
                                checked={!(settings[day.key as keyof typeof settings] as any).closed}
                                onCheckedChange={(checked) => handleOperatingHoursChange(day.key, 'closed', !checked)}
                              />
                              <span className="text-sm text-gray-600">
                                {(settings[day.key as keyof typeof settings] as any).closed ? 'Closed' : 'Open'}
                              </span>
                            </div>
                            {!((settings[day.key as keyof typeof settings] as any).closed) && (
                              <>
                                <Input
                                  type="time"
                                  value={(settings[day.key as keyof typeof settings] as any).open}
                                  onChange={(e) => handleOperatingHoursChange(day.key, 'open', e.target.value)}
                                  className="w-32"
                                />
                                <span className="text-sm text-gray-600">to</span>
                                <Input
                                  type="time"
                                  value={(settings[day.key as keyof typeof settings] as any).close}
                                  onChange={(e) => handleOperatingHoursChange(day.key, 'close', e.target.value)}
                                  className="w-32"
                                />
                              </>
                            )}
                          </div>
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>

                {/* Notifications */}
                <TabsContent value="notifications">
                  <Card>
                    <CardHeader>
                      <CardTitle>Notification Preferences</CardTitle>
                      <CardDescription>Configure how you receive notifications</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                      <div className="space-y-4">
                        <div className="flex items-center justify-between">
                          <div>
                            <Label className="text-sm font-medium">Email Notifications</Label>
                            <p className="text-sm text-gray-600">Receive notifications via email</p>
                          </div>
                          <Switch
                            checked={settings.emailNotifications}
                            onCheckedChange={(checked) => handleSettingChange('emailNotifications', checked)}
                          />
                        </div>
                        <div className="flex items-center justify-between">
                          <div>
                            <Label className="text-sm font-medium">SMS Notifications</Label>
                            <p className="text-sm text-gray-600">Receive notifications via text message</p>
                          </div>
                          <Switch
                            checked={settings.smsNotifications}
                            onCheckedChange={(checked) => handleSettingChange('smsNotifications', checked)}
                          />
                        </div>
                        <div className="flex items-center justify-between">
                          <div>
                            <Label className="text-sm font-medium">Booking Reminders</Label>
                            <p className="text-sm text-gray-600">Send automatic reminders to customers</p>
                          </div>
                          <Switch
                            checked={settings.bookingReminders}
                            onCheckedChange={(checked) => handleSettingChange('bookingReminders', checked)}
                          />
                        </div>
                        <div className="flex items-center justify-between">
                          <div>
                            <Label className="text-sm font-medium">Marketing Emails</Label>
                            <p className="text-sm text-gray-600">Send promotional emails to customers</p>
                          </div>
                          <Switch
                            checked={settings.marketingEmails}
                            onCheckedChange={(checked) => handleSettingChange('marketingEmails', checked)}
                          />
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>

                {/* Booking Settings */}
                <TabsContent value="booking">
                  <Card>
                    <CardHeader>
                      <CardTitle>Booking Settings</CardTitle>
                      <CardDescription>Configure booking policies and rules</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div className="space-y-2">
                          <Label htmlFor="advanceBooking">Advance Booking (Days)</Label>
                          <Input
                            id="advanceBooking"
                            type="number"
                            value={settings.advanceBookingDays}
                            onChange={(e) => handleSettingChange('advanceBookingDays', parseInt(e.target.value))}
                          />
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="cancellationHours">Cancellation Notice (Hours)</Label>
                          <Input
                            id="cancellationHours"
                            type="number"
                            value={settings.cancellationHours}
                            onChange={(e) => handleSettingChange('cancellationHours', parseInt(e.target.value))}
                          />
                        </div>
                      </div>
                      <div className="space-y-4">
                        <div className="flex items-center justify-between">
                          <div>
                            <Label className="text-sm font-medium">Auto-confirm Bookings</Label>
                            <p className="text-sm text-gray-600">Automatically confirm new bookings</p>
                          </div>
                          <Switch
                            checked={settings.autoConfirmBookings}
                            onCheckedChange={(checked) => handleSettingChange('autoConfirmBookings', checked)}
                          />
                        </div>
                        <div className="flex items-center justify-between">
                          <div>
                            <Label className="text-sm font-medium">Require Deposit</Label>
                            <p className="text-sm text-gray-600">Require payment deposit for bookings</p>
                          </div>
                          <Switch
                            checked={settings.requireDeposit}
                            onCheckedChange={(checked) => handleSettingChange('requireDeposit', checked)}
                          />
                        </div>
                        {settings.requireDeposit && (
                          <div className="space-y-2">
                            <Label htmlFor="depositAmount">Deposit Amount (AED)</Label>
                            <Input
                              id="depositAmount"
                              type="number"
                              value={settings.depositAmount}
                              onChange={(e) => handleSettingChange('depositAmount', parseFloat(e.target.value))}
                            />
                          </div>
                        )}
                      </div>

                      <div className="pt-4 border-t space-y-4">
                        <h3 className="text-lg font-medium">Calendar Display Settings</h3>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                          <div className="space-y-2">
                            <Label htmlFor="timeSlotGap">Time Slot Gap</Label>
                            <Select
                              value={String(settings.calendarDisplaySettings.timeSlotGap)}
                              onValueChange={(value) =>
                                handleCalendarDisplaySettingChange('timeSlotGap', parseInt(value, 10))
                              }
                            >
                              <SelectTrigger>
                                <SelectValue />
                              </SelectTrigger>
                              <SelectContent>
                                <SelectItem value="15">15 minutes</SelectItem>
                                <SelectItem value="30">30 minutes</SelectItem>
                                <SelectItem value="45">45 minutes</SelectItem>
                                <SelectItem value="60">60 minutes</SelectItem>
                                <SelectItem value="120">120 minutes</SelectItem>
                              </SelectContent>
                            </Select>
                          </div>

                          <div className="space-y-2">
                            <Label htmlFor="layoutMode">Layout Mode</Label>
                            <Select
                              value={settings.calendarDisplaySettings.layoutMode}
                              onValueChange={(value: 'time-top' | 'employee-top') =>
                                handleCalendarDisplaySettingChange('layoutMode', value)
                              }
                            >
                              <SelectTrigger>
                                <SelectValue />
                              </SelectTrigger>
                              <SelectContent>
                                <SelectItem value="time-top">Time Top</SelectItem>
                                <SelectItem value="employee-top">Employee Top</SelectItem>
                              </SelectContent>
                            </Select>
                          </div>

                          <div className="space-y-2">
                            <Label htmlFor="businessHoursStart">Business Start Hour (24h)</Label>
                            <Input
                              id="businessHoursStart"
                              type="number"
                              min={0}
                              max={23}
                              value={settings.calendarDisplaySettings.businessHours.start}
                              onChange={(e) =>
                                handleCalendarDisplaySettingChange('businessHours', {
                                  ...settings.calendarDisplaySettings.businessHours,
                                  start: Number(e.target.value),
                                })
                              }
                            />
                          </div>

                          <div className="space-y-2">
                            <Label htmlFor="businessHoursEnd">Business End Hour (24h)</Label>
                            <Input
                              id="businessHoursEnd"
                              type="number"
                              min={0}
                              max={23}
                              value={settings.calendarDisplaySettings.businessHours.end}
                              onChange={(e) =>
                                handleCalendarDisplaySettingChange('businessHours', {
                                  ...settings.calendarDisplaySettings.businessHours,
                                  end: Number(e.target.value),
                                })
                              }
                            />
                          </div>
                        </div>

                        <div className="space-y-2">
                          <Label htmlFor="hiddenHours">Hidden Hours (comma-separated, 24h)</Label>
                          <Input
                            id="hiddenHours"
                            placeholder="13,14"
                            value={settings.calendarDisplaySettings.hiddenHours.join(',')}
                            onChange={(e) => {
                              const parsed = e.target.value
                                .split(',')
                                .map((h) => Number(h.trim()))
                                .filter((h) => Number.isInteger(h) && h >= 0 && h <= 23);
                              handleCalendarDisplaySettingChange('hiddenHours', parsed);
                            }}
                          />
                        </div>

                        <div className="space-y-2">
                          <Label htmlFor="bookingTotalMode">Booking Total Value Display</Label>
                          <Select
                            value={settings.calendarDisplaySettings.totalValueDisplayMode}
                            onValueChange={(value: 'both' | 'with-tax' | 'without-tax') =>
                              handleCalendarDisplaySettingChange('totalValueDisplayMode', value)
                            }
                          >
                            <SelectTrigger id="bookingTotalMode">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="both">Show Both (With Tax and Excluding Tax)</SelectItem>
                              <SelectItem value="with-tax">Show With Tax Only</SelectItem>
                              <SelectItem value="without-tax">Show Excluding Tax Only</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>

                        <div className="space-y-2">
                          <Label htmlFor="invoiceTotalMode">Invoice Calculation Mode</Label>
                          <Select
                            value={settings.calendarDisplaySettings.invoiceValueDisplayMode}
                            onValueChange={(value: 'with-tax' | 'without-tax') =>
                              handleCalendarDisplaySettingChange('invoiceValueDisplayMode', value)
                            }
                          >
                            <SelectTrigger id="invoiceTotalMode">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="with-tax">With Tax (Default 5%)</SelectItem>
                              <SelectItem value="without-tax">Without Tax (Service Total Only)</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>

                        <div className="space-y-2">
                          <Label htmlFor="invoiceDisclaimerTemplate">Invoice Footer Disclaimer</Label>
                          <Textarea
                            id="invoiceDisclaimerTemplate"
                            value={settings.invoiceDisclaimerTemplate}
                            onChange={(e) => handleSettingChange('invoiceDisclaimerTemplate', e.target.value)}
                            rows={4}
                            placeholder="This invoice is generated by system with current date and time: {{dateTime}}. No refund available on any service, product, or e-wallet transaction."
                          />
                          <p className="text-xs text-gray-500">
                            Use {'{{dateTime}}'} to auto insert current date and time on invoice generation.
                          </p>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>

                {/* Payment Settings */}
                <TabsContent value="payment">
                  <Card>
                    <CardHeader>
                      <CardTitle>Payment Settings</CardTitle>
                      <CardDescription>Configure payment methods and tax rates</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                      <div className="space-y-4">
                        <div className="flex items-center justify-between">
                          <div>
                            <Label className="text-sm font-medium">Accept Cash</Label>
                            <p className="text-sm text-gray-600">Allow cash payments at the shop</p>
                          </div>
                          <Switch
                            checked={settings.acceptCash}
                            onCheckedChange={(checked) => handleSettingChange('acceptCash', checked)}
                          />
                        </div>
                        <div className="flex items-center justify-between">
                          <div>
                            <Label className="text-sm font-medium">Accept Credit/Debit Cards</Label>
                            <p className="text-sm text-gray-600">Allow card payments</p>
                          </div>
                          <Switch
                            checked={settings.acceptCard}
                            onCheckedChange={(checked) => handleSettingChange('acceptCard', checked)}
                          />
                        </div>
                        <div className="flex items-center justify-between">
                          <div>
                            <Label className="text-sm font-medium">Accept Check Payments</Label>
                            <p className="text-sm text-gray-600">Allow bank check payments</p>
                          </div>
                          <Switch
                            checked={settings.acceptCheck}
                            onCheckedChange={(checked) => handleSettingChange('acceptCheck', checked)}
                          />
                        </div>
                        <div className="flex items-center justify-between">
                          <div>
                            <Label className="text-sm font-medium">Accept Digital Payments</Label>
                            <p className="text-sm text-gray-600">Allow Apple Pay, Google Pay, etc.</p>
                          </div>
                          <Switch
                            checked={settings.acceptDigital}
                            onCheckedChange={(checked) => handleSettingChange('acceptDigital', checked)}
                          />
                        </div>
                        <div className="flex items-center justify-between">
                          <div>
                            <Label className="text-sm font-medium">Accept E-Wallet Payments</Label>
                            <p className="text-sm text-gray-600">Allow customer e-wallet balance usage</p>
                          </div>
                          <Switch
                            checked={settings.acceptEwallet}
                            onCheckedChange={(checked) => handleSettingChange('acceptEwallet', checked)}
                          />
                        </div>
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="currency">Currency</Label>
                        <Select value={currency} onValueChange={(value: any) => setCurrency(value)}>
                          <SelectTrigger>
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="AED">AED - UAE Dirham (د.إ)</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="taxRate">Tax Rate (%)</Label>
                        <Input
                          id="taxRate"
                          type="number"
                          step="0.01"
                          value={settings.taxRate}
                          onChange={(e) => handleSettingChange('taxRate', parseFloat(e.target.value))}
                        />
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>
              </Tabs>
            </div>
          </div>
        </div>
      </div>
    </ProtectedRoute>
  );
}