'use client';

import { useState, useEffect, useRef } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Separator } from "@/components/ui/separator";
import { Settings, User, Bell, Shield, Palette, Database, Mail, Phone, MapPin, Clock, Save, RefreshCw, Upload, Image as ImageIcon, X, Link } from "lucide-react";
import ProtectedRoute from "@/components/ProtectedRoute";
import { AdminSidebar, AdminMobileSidebar } from "@/components/admin/AdminSidebar";
import { cn } from "@/lib/utils";
import { useAuth } from "@/contexts/AuthContext";
import { useRouter } from "next/navigation";

// Firebase imports
import { doc, setDoc, getDoc, onSnapshot } from "firebase/firestore";
import { ref, uploadBytes, getDownloadURL } from "firebase/storage";
import { db, storage } from "@/lib/firebase";
import { toast } from "sonner";

export default function SuperAdminSettings() {
  const { user, logout } = useAuth();
  const router = useRouter();
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [hasLoaded, setHasLoaded] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [logoMethod, setLogoMethod] = useState<'upload' | 'url'>('url'); // New state for logo method
  const [logoUrlInput, setLogoUrlInput] = useState('/manofcavebradning.png'); // New state for URL input

  const DEFAULT_BUSINESS_SETTINGS = {
    businessName: "Man of Cave",
    businessEmail: "info@manofcave.com",
    businessPhone: "0545354361",
    businessLogo: "/manofcavebradning.png",
  };

  const handleLogout = () => {
    logout();
    router.push('/login');
  };

  // Initial settings state
  const [settings, setSettings] = useState({
    ...DEFAULT_BUSINESS_SETTINGS,
    
    businessLogo: DEFAULT_BUSINESS_SETTINGS.businessLogo,
    businessLogoFile: null as File | null,
    emailNotifications: true,
    smsNotifications: false,
    pushNotifications: true,
    bookingReminders: true,
    paymentNotifications: true,
    systemAlerts: true,
    acceptCash: true,
    acceptCard: true,
    acceptCheck: true,
    acceptDigital: true,
    acceptEwallet: true,
    taxRate: 5,
    paymentGateway: {
      provider: 'totalpay' as 'none' | 'totalpay',
      totalPay: {
        enabled: true,
        baseUrl: 'https://dashboard.totalpay.global',
        createInvoiceEndpoint: '/api/customer-invoices/create',
        merchantId: '0627f618-340b-11ff-acee-daf501054ef1',
        apiKey: '0625df36-340b-11ff-86e2-daf501054ef1',
        apiSecret: '',
        successUrl: '',
        cancelUrl: '',
        webhookUrl: '',
      },
    },
    twoFactorAuth: false,
    sessionTimeout: "30",
    passwordExpiry: "90",
    loginAttempts: "5",
    theme: "luxury",
    primaryColor: "#1a1a1a",
    secondaryColor: "#d4af37",
    accentColor: "#8b4513",
    autoBackup: true,
    backupFrequency: "daily",
    dataRetention: "365",
    maintenanceMode: false,
    debugMode: false,

    // Calendar Display Settings (used by booking calendars)
    calendarDisplaySettings: {
      timeSlotGap: 30,
      layoutMode: 'time-top' as 'time-top' | 'employee-top',
      businessHours: { start: 9, end: 22 },
      hiddenHours: [] as number[],
      totalValueDisplayMode: 'both' as 'both' | 'with-tax' | 'without-tax',
      invoiceValueDisplayMode: 'with-tax' as 'with-tax' | 'without-tax',
    }
    ,

    // Invoice disclaimer footer (shown in generated invoice PDF)
    invoiceDisclaimerTemplate:
      'This invoice is generated by system with current date and time: {{dateTime}}. No refund available on any service, product, or e-wallet transaction.'
  });

  // Load settings from Firebase in real time
  useEffect(() => {
    const settingsRef = doc(db, "general", "settings");

    setLoading(true);
    const unsubscribe = onSnapshot(
      settingsRef,
      async (settingsSnap) => {
        try {
          if (settingsSnap.exists()) {
            const data = settingsSnap.data();
            const normalized: any = {
              ...DEFAULT_BUSINESS_SETTINGS,
              ...data,
            };

            const isLegacyName = typeof data.businessName === 'string' && data.businessName.toLowerCase().includes('downtown');
            const isLegacyEmail = typeof data.businessEmail === 'string' && data.businessEmail.toLowerCase().includes('downtown@manofcave.com');
            const needsDefaults =
              !data.businessName ||
              !data.businessEmail ||
              !data.businessPhone ||
              !data.businessLogo ||
              isLegacyName ||
              isLegacyEmail;

            const finalBusiness = needsDefaults
              ? {
                  businessName: DEFAULT_BUSINESS_SETTINGS.businessName,
                  businessEmail: DEFAULT_BUSINESS_SETTINGS.businessEmail,
                  businessPhone: DEFAULT_BUSINESS_SETTINGS.businessPhone,
                  businessLogo: DEFAULT_BUSINESS_SETTINGS.businessLogo,
                }
              : {
                  businessName: normalized.businessName,
                  businessEmail: normalized.businessEmail,
                  businessPhone: normalized.businessPhone,
                  businessLogo: normalized.businessLogo,
                };

            setSettings(prev => ({
              ...prev,
              ...normalized,
              ...finalBusiness,
              taxRate: Number.isFinite(Number(normalized.taxRate)) ? Number(normalized.taxRate) : prev.taxRate,
              paymentGateway: {
                provider: normalized.paymentGateway?.provider ?? prev.paymentGateway.provider,
                totalPay: {
                  ...prev.paymentGateway.totalPay,
                  ...(normalized.paymentGateway?.totalPay || {}),
                },
              },
              calendarDisplaySettings: {
                ...prev.calendarDisplaySettings,
                ...(normalized.calendarDisplaySettings || {}),
                businessHours: {
                  ...prev.calendarDisplaySettings.businessHours,
                  ...(normalized.calendarDisplaySettings?.businessHours || {}),
                },
                hiddenHours: Array.isArray(normalized.calendarDisplaySettings?.hiddenHours)
                  ? normalized.calendarDisplaySettings.hiddenHours
                  : prev.calendarDisplaySettings.hiddenHours,
              },
              businessLogoFile: null
            }));

            setLogoMethod('url');
            setLogoUrlInput(finalBusiness.businessLogo);

            if (needsDefaults) {
              await setDoc(
                settingsRef,
                {
                  ...finalBusiness,
                  updatedAt: new Date().toISOString(),
                  updatedBy: user?.email || "system",
                },
                { merge: true }
              );
            }

            if (!hasLoaded) {
              toast.success("Settings loaded successfully from Firebase");
              setHasLoaded(true);
            }
          } else {
            const seeded = {
              ...DEFAULT_BUSINESS_SETTINGS,
              updatedAt: new Date().toISOString(),
              updatedBy: user?.email || "system",
            };
            await setDoc(settingsRef, seeded, { merge: true });
            setSettings(prev => ({
              ...prev,
              ...seeded,
              businessLogoFile: null
            }));
            setLogoMethod('url');
            setLogoUrlInput(DEFAULT_BUSINESS_SETTINGS.businessLogo);
            if (!hasLoaded) {
              toast.info("No settings found. Default business data created.");
              setHasLoaded(true);
            }
          }
        } catch (error) {
          console.error("Error loading settings from Firebase:", error);
          toast.error("Failed to load settings from Firebase");
        } finally {
          setLoading(false);
        }
      },
      (error) => {
        console.error("Error listening to settings:", error);
        toast.error("Failed to listen to settings updates");
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [hasLoaded, user?.email]);

  // Handle file selection for logo
  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (!file.type.startsWith('image/')) {
        toast.error('Please select an image file (JPG, PNG, etc.)');
        return;
      }
      
      if (file.size > 5 * 1024 * 1024) {
        toast.error('Image size should be less than 5MB');
        return;
      }
      
      const previewUrl = URL.createObjectURL(file);
      
      setSettings(prev => ({
        ...prev,
        businessLogo: previewUrl,
        businessLogoFile: file
      }));
      
      toast.success('Logo selected. Click Save to upload to Firebase.');
    }
  };

  // Handle URL input for logo
  const handleUrlInputChange = (url: string) => {
    setLogoUrlInput(url);
    
    // Validate URL format
    if (url) {
      try {
        new URL(url); // Check if it's a valid URL
        setSettings(prev => ({
          ...prev,
          businessLogo: url,
          businessLogoFile: null
        }));
      } catch (error) {
        // Invalid URL, don't update the logo
      }
    } else {
      setSettings(prev => ({
        ...prev,
        businessLogo: "",
        businessLogoFile: null
      }));
    }
  };

  // Apply URL as logo
  const applyUrlAsLogo = () => {
    if (!logoUrlInput.trim()) {
      toast.error('Please enter a valid URL');
      return;
    }

    try {
      // Validate URL
      new URL(logoUrlInput);
      
      setSettings(prev => ({
        ...prev,
        businessLogo: logoUrlInput,
        businessLogoFile: null
      }));
      
      toast.success('Logo URL applied successfully');
    } catch (error) {
      toast.error('Please enter a valid URL (e.g., https://example.com/logo.png)');
    }
  };

  // Remove logo
  const removeLogo = () => {
    setSettings(prev => ({
      ...prev,
      businessLogo: "",
      businessLogoFile: null
    }));
    setLogoUrlInput('');
  };

  // Trigger file input click
  const triggerFileInput = () => {
    fileInputRef.current?.click();
  };

  // Upload image to Firebase Storage
  const uploadImageToFirebase = async (file: File): Promise<string> => {
    try {
      setUploading(true);
      
      if (!storage) {
        throw new Error('Firebase Storage is not initialized.');
      }
      
      const timestamp = Date.now();
      const filename = `business-logo-${timestamp}-${file.name.replace(/\s+/g, '-')}`;
      
      const storageRef = ref(storage, `business-logos/${filename}`);
      const snapshot = await uploadBytes(storageRef, file);
      const downloadURL = await getDownloadURL(snapshot.ref);
      
      console.log('✅ Image uploaded to Firebase Storage:', downloadURL);
      return downloadURL;
    } catch (error: any) {
      console.error('❌ Error uploading image:', error);
      toast.error(`Failed to upload image: ${error.message || 'Unknown error'}`);
      throw error;
    } finally {
      setUploading(false);
    }
  };

  // Firebase mein settings save karna - SIMPLIFIED
  const saveSettingsToFirebase = async (
    overrideSettings?: typeof settings,
    overrideLogo?: { method?: 'upload' | 'url'; urlInput?: string }
  ) => {
    try {
      setSaving(true);

      const source = overrideSettings ?? settings;
      const effectiveLogoMethod = overrideLogo?.method ?? logoMethod;
      const effectiveLogoUrlInput = overrideLogo?.urlInput ?? logoUrlInput;
      let logoUrl = source.businessLogo;
      
      // Agar upload method hai aur file hai to upload karein
      if (effectiveLogoMethod === 'upload' && source.businessLogoFile) {
        try {
          toast.info('Uploading logo to Firebase Storage...');
          logoUrl = await uploadImageToFirebase(source.businessLogoFile);
          toast.success('Logo uploaded successfully!');
        } catch (error) {
          toast.error('Failed to upload logo');
          return false;
        }
      }
      // Agar URL method hai to direct use karein
      else if (effectiveLogoMethod === 'url' && effectiveLogoUrlInput) {
        logoUrl = effectiveLogoUrlInput;
      }
      
      // Prepare data for Firebase
      const settingsData = {
        businessName: source.businessName,
        businessEmail: source.businessEmail,
        businessPhone: source.businessPhone,
        
        businessLogo: logoUrl,
        emailNotifications: source.emailNotifications,
        smsNotifications: source.smsNotifications,
        pushNotifications: source.pushNotifications,
        bookingReminders: source.bookingReminders,
        paymentNotifications: source.paymentNotifications,
        systemAlerts: source.systemAlerts,
        acceptCash: source.acceptCash,
        acceptCard: source.acceptCard,
        acceptCheck: source.acceptCheck,
        acceptDigital: source.acceptDigital,
        acceptEwallet: source.acceptEwallet,
        paymentGateway: source.paymentGateway,
        taxRate: source.taxRate,
        twoFactorAuth: source.twoFactorAuth,
        sessionTimeout: source.sessionTimeout,
        passwordExpiry: source.passwordExpiry,
        loginAttempts: source.loginAttempts,
        theme: source.theme,
        primaryColor: source.primaryColor,
        secondaryColor: source.secondaryColor,
        accentColor: source.accentColor,
        autoBackup: source.autoBackup,
        backupFrequency: source.backupFrequency,
        dataRetention: source.dataRetention,
        maintenanceMode: source.maintenanceMode,
        debugMode: source.debugMode,
        calendarDisplaySettings: source.calendarDisplaySettings,
        invoiceDisclaimerTemplate: source.invoiceDisclaimerTemplate,
        updatedAt: new Date().toISOString(),
        updatedBy: user?.email || "unknown",
        lastUpdated: new Date().toLocaleString()
      };

      const settingsRef = doc(db, "general", "settings");
      await setDoc(settingsRef, settingsData, { merge: true });
      
      toast.success("✅ All settings saved to Firebase!");
      
      // Reset file reference
      if (effectiveLogoMethod === 'upload') {
        setSettings(prev => ({ 
          ...prev, 
          businessLogoFile: null,
          businessLogo: logoUrl
        }));
      }
      
      return true;
    } catch (error: any) {
      console.error("❌ Error saving settings to Firebase:", error);
      toast.error(`❌ Failed to save: ${error.message || 'Unknown error'}`);
      return false;
    } finally {
      setSaving(false);
    }
  };

  // Save button handler - SIMPLIFIED
  const handleSave = async () => {
    // Validate required fields
    if (!settings.businessName.trim()) {
      toast.error('Business Name is required');
      return;
    }
    
    if (!settings.businessEmail.trim()) {
      toast.error('Business Email is required');
      return;
    }
    
    if (!settings.businessPhone.trim()) {
      toast.error('Business Phone is required');
      return;
    }
    
    // Validate logo based on method
    if (logoMethod === 'upload' && !settings.businessLogoFile && !settings.businessLogo.includes('firebasestorage')) {
      toast.warning('Please select a logo file or switch to URL method');
      return;
    }
    
    if (logoMethod === 'url' && !logoUrlInput.trim()) {
      toast.error('Please enter a logo URL');
      return;
    }
    
    const saved = await saveSettingsToFirebase();
    if (saved) {
      // Success message already shown
    }
  };

  // Reset button handler
  const handleReset = async () => {
    const resetSettings = {
      ...settings,
      ...DEFAULT_BUSINESS_SETTINGS,
      businessLogoFile: null as File | null,
    };

    setSettings(resetSettings);
    setLogoMethod('url');
    setLogoUrlInput(DEFAULT_BUSINESS_SETTINGS.businessLogo);

    const saved = await saveSettingsToFirebase(resetSettings, {
      method: 'url',
      urlInput: DEFAULT_BUSINESS_SETTINGS.businessLogo,
    });

    if (saved) {
      toast.success('Business details reset to current brand data.');
    }
  };

  // Input change handler
  const handleInputChange = (field: string, value: any) => {
    setSettings(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleCalendarDisplaySettingChange = (
    key: 'timeSlotGap' | 'layoutMode' | 'businessHours' | 'hiddenHours' | 'totalValueDisplayMode' | 'invoiceValueDisplayMode',
    value: any
  ) => {
    setSettings((prev) => ({
      ...prev,
      calendarDisplaySettings: {
        ...prev.calendarDisplaySettings,
        [key]: value,
      },
    }));
  };

  const handlePaymentGatewayChange = (key: string, value: any) => {
    setSettings((prev) => ({
      ...prev,
      paymentGateway: {
        ...prev.paymentGateway,
        totalPay: {
          ...prev.paymentGateway.totalPay,
          [key]: value,
        },
      },
    }));
  };

  const updateNotificationSetting = async (field: string, value: boolean) => {
    setSettings(prev => ({
      ...prev,
      [field]: value
    }));

    try {
      const settingsRef = doc(db, "general", "settings");
      await setDoc(settingsRef, {
        [field]: value,
        updatedAt: new Date().toISOString(),
        updatedBy: user?.email || "system",
      }, { merge: true });
    } catch (error) {
      console.error("Error updating notification setting:", error);
      toast.error("Failed to update notification setting");
    }
  };

  return (
    <ProtectedRoute requiredRole="super_admin">
      <div className="flex h-screen bg-gray-50">
        {/* Sidebar */}
        <AdminSidebar role="super_admin" onLogout={handleLogout}
          isOpen={sidebarOpen}
          onToggle={() => setSidebarOpen(!sidebarOpen)} />

        {/* Main Content */}
        <div className={cn(
          "flex-1 flex flex-col transition-all duration-300 ease-in-out",
          sidebarOpen ? "lg:ml-0" : "lg:ml-0"
        )}>
          {/* Header */}
          <header className="bg-white shadow-sm border-b">
            <div className="flex items-center justify-between px-4 py-4 lg:px-8">
              <div className="flex items-center gap-4">
                <AdminMobileSidebar role="super_admin" onLogout={handleLogout}
                  isOpen={sidebarOpen}
                  onToggle={() => setSidebarOpen(!sidebarOpen)} />
                <div>
                  <h1 className="text-2xl font-bold text-gray-900">System Settings</h1>
                  <p className="text-sm text-gray-600">Configure system-wide settings and preferences</p>
                </div>
              </div>
              <div className="flex items-center gap-4">
                <Button variant="outline" onClick={handleReset} disabled={loading || saving || uploading}>
                  <RefreshCw className="w-4 h-4 mr-2" />
                  Reset
                </Button>
                <Button onClick={handleSave} disabled={loading || saving || uploading}>
                  <Save className="w-4 h-4 mr-2" />
                  {saving ? "Saving..." : uploading ? "Uploading..." : "Save"}
                </Button>
                <span className="text-sm text-gray-600 hidden sm:block">Welcome, {user?.email}</span>
                <Button variant="outline" onClick={handleLogout} className="hidden sm:flex">
                  Logout
                </Button>
              </div>
            </div>
          </header>

          {/* Content */}
          <div className="flex-1 overflow-auto">
            <div className="p-4 lg:p-8">
              {loading ? (
                <div className="flex justify-center items-center h-64">
                  <div className="text-center">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gray-900 mx-auto"></div>
                    <p className="mt-4 text-gray-600">Loading settings from Firebase...</p>
                  </div>
                </div>
              ) : (
                <Tabs defaultValue="notifications" className="space-y-6">
                  <TabsList className="grid w-full grid-cols-2">
                    <TabsTrigger value="notifications" className="flex items-center gap-2">
                      <Bell className="w-4 h-4" />
                      Notifications
                    </TabsTrigger>
                    <TabsTrigger value="appearance" className="flex items-center gap-2">
                      <Palette className="w-4 h-4" />
                      Appearance
                    </TabsTrigger>
                  </TabsList>

                  {/* Notification Settings */}
                  <TabsContent value="notifications">
                    <Card>
                      <CardHeader>
                        <CardTitle>Notification Preferences</CardTitle>
                        <CardDescription>Configure how and when you receive notifications</CardDescription>
                      </CardHeader>
                      <CardContent className="space-y-6">
                        <div className="space-y-4">
                          <div className="flex items-center justify-between">
                            <div className="space-y-0.5">
                              <Label>Email Notifications</Label>
                              <p className="text-sm text-gray-600">Receive notifications via email</p>
                            </div>
                            <Switch
                              checked={settings.emailNotifications}
                              onCheckedChange={(checked) => updateNotificationSetting('emailNotifications', checked)}
                            />
                          </div>

                          <div className="flex items-center justify-between">
                            <div className="space-y-0.5">
                              <Label>SMS Notifications</Label>
                              <p className="text-sm text-gray-600">Receive notifications via SMS</p>
                            </div>
                            <Switch
                              checked={settings.smsNotifications}
                              onCheckedChange={(checked) => updateNotificationSetting('smsNotifications', checked)}
                            />
                          </div>

                          <div className="flex items-center justify-between">
                            <div className="space-y-0.5">
                              <Label>Push Notifications</Label>
                              <p className="text-sm text-gray-600">Receive push notifications in browser</p>
                            </div>
                            <Switch
                              checked={settings.pushNotifications}
                              onCheckedChange={(checked) => updateNotificationSetting('pushNotifications', checked)}
                            />
                          </div>
                        </div>

                        <Separator />

                        <div className="space-y-4">
                          <h3 className="text-lg font-medium">Notification Types</h3>

                          <div className="flex items-center justify-between">
                            <div className="space-y-0.5">
                              <Label>Booking Reminders</Label>
                              <p className="text-sm text-gray-600">Notify about upcoming appointments</p>
                            </div>
                            <Switch
                              checked={settings.bookingReminders}
                              onCheckedChange={(checked) => updateNotificationSetting('bookingReminders', checked)}
                            />
                          </div>

                          <div className="flex items-center justify-between">
                            <div className="space-y-0.5">
                              <Label>Payment Notifications</Label>
                              <p className="text-sm text-gray-600">Notify about payment activities</p>
                            </div>
                            <Switch
                              checked={settings.paymentNotifications}
                              onCheckedChange={(checked) => updateNotificationSetting('paymentNotifications', checked)}
                            />
                          </div>

                          <div className="flex items-center justify-between">
                            <div className="space-y-0.5">
                              <Label>System Alerts</Label>
                              <p className="text-sm text-gray-600">Notify about system issues and updates</p>
                            </div>
                            <Switch
                              checked={settings.systemAlerts}
                              onCheckedChange={(checked) => updateNotificationSetting('systemAlerts', checked)}
                            />
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  </TabsContent>

                  {/* Appearance Settings */}
                  <TabsContent value="appearance">
                    <Card>
                      <CardHeader>
                        <CardTitle>Booking Calendar Display</CardTitle>
                        <CardDescription>Manage booking calendar layout and value display</CardDescription>
                      </CardHeader>
                      <CardContent className="space-y-6">
                        <div className="space-y-4">
                          <h3 className="text-lg font-medium">Booking Calendar Display</h3>

                          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div className="space-y-2">
                              <Label htmlFor="calendarTimeSlotGap">Time Slot Gap</Label>
                              <Select
                                value={String(settings.calendarDisplaySettings.timeSlotGap)}
                                onValueChange={(value) =>
                                  handleCalendarDisplaySettingChange('timeSlotGap', parseInt(value, 10))
                                }
                              >
                                <SelectTrigger id="calendarTimeSlotGap">
                                  <SelectValue />
                                </SelectTrigger>
                                <SelectContent>
                                  <SelectItem value="15">15 minutes</SelectItem>
                                  <SelectItem value="30">30 minutes</SelectItem>
                                  <SelectItem value="45">45 minutes</SelectItem>
                                  <SelectItem value="60">60 minutes</SelectItem>
                                  <SelectItem value="120">120 minutes</SelectItem>
                                </SelectContent>
                              </Select>
                            </div>

                            <div className="space-y-2">
                              <Label htmlFor="calendarLayoutMode">Layout Mode</Label>
                              <Select
                                value={settings.calendarDisplaySettings.layoutMode}
                                onValueChange={(value: 'time-top' | 'employee-top') =>
                                  handleCalendarDisplaySettingChange('layoutMode', value)
                                }
                              >
                                <SelectTrigger id="calendarLayoutMode">
                                  <SelectValue />
                                </SelectTrigger>
                                <SelectContent>
                                  <SelectItem value="time-top">Time Top</SelectItem>
                                  <SelectItem value="employee-top">Employee Top</SelectItem>
                                </SelectContent>
                              </Select>
                            </div>

                            <div className="space-y-2">
                              <Label htmlFor="calendarBusinessStart">Business Start Hour (24h)</Label>
                              <Input
                                id="calendarBusinessStart"
                                type="number"
                                min={0}
                                max={23}
                                value={settings.calendarDisplaySettings.businessHours.start}
                                onChange={(e) =>
                                  handleCalendarDisplaySettingChange('businessHours', {
                                    ...settings.calendarDisplaySettings.businessHours,
                                    start: Number(e.target.value),
                                  })
                                }
                              />
                            </div>

                            <div className="space-y-2">
                              <Label htmlFor="calendarBusinessEnd">Business End Hour (24h)</Label>
                              <Input
                                id="calendarBusinessEnd"
                                type="number"
                                min={0}
                                max={23}
                                value={settings.calendarDisplaySettings.businessHours.end}
                                onChange={(e) =>
                                  handleCalendarDisplaySettingChange('businessHours', {
                                    ...settings.calendarDisplaySettings.businessHours,
                                    end: Number(e.target.value),
                                  })
                                }
                              />
                            </div>
                          </div>

                          <div className="space-y-2">
                            <Label htmlFor="calendarHiddenHours">Hidden Hours (comma-separated, 24h)</Label>
                            <Input
                              id="calendarHiddenHours"
                              placeholder="13,14"
                              value={settings.calendarDisplaySettings.hiddenHours.join(',')}
                              onChange={(e) => {
                                const parsed = e.target.value
                                  .split(',')
                                  .map((h) => Number(h.trim()))
                                  .filter((h) => Number.isInteger(h) && h >= 0 && h <= 23);
                                handleCalendarDisplaySettingChange('hiddenHours', parsed);
                              }}
                            />
                          </div>

                          <div className="space-y-2">
                            <Label htmlFor="calendarTotalValueDisplayMode">Booking Total Value Display</Label>
                            <Select
                              value={settings.calendarDisplaySettings.totalValueDisplayMode}
                              onValueChange={(value: 'both' | 'with-tax' | 'without-tax') =>
                                handleCalendarDisplaySettingChange('totalValueDisplayMode', value)
                              }
                            >
                              <SelectTrigger id="calendarTotalValueDisplayMode">
                                <SelectValue />
                              </SelectTrigger>
                              <SelectContent>
                                <SelectItem value="both">Show Both (With Tax and Excluding Tax)</SelectItem>
                                <SelectItem value="with-tax">Show With Tax Only</SelectItem>
                                <SelectItem value="without-tax">Show Excluding Tax Only</SelectItem>
                              </SelectContent>
                            </Select>
                          </div>

                          <div className="space-y-2">
                            <Label htmlFor="calendarInvoiceValueDisplayMode">Invoice Calculation Mode</Label>
                            <Select
                              value={settings.calendarDisplaySettings.invoiceValueDisplayMode}
                              onValueChange={(value: 'with-tax' | 'without-tax') =>
                                handleCalendarDisplaySettingChange('invoiceValueDisplayMode', value)
                              }
                            >
                              <SelectTrigger id="calendarInvoiceValueDisplayMode">
                                <SelectValue />
                              </SelectTrigger>
                              <SelectContent>
                                <SelectItem value="with-tax">With Tax (Default 5%)</SelectItem>
                                <SelectItem value="without-tax">Without Tax (Service Total Only)</SelectItem>
                              </SelectContent>
                            </Select>
                          </div>

                          <div className="space-y-2">
                            <Label htmlFor="invoiceDisclaimerTemplate">Invoice Footer Disclaimer</Label>
                            <Textarea
                              id="invoiceDisclaimerTemplate"
                              value={settings.invoiceDisclaimerTemplate}
                              onChange={(e) => handleInputChange('invoiceDisclaimerTemplate', e.target.value)}
                              rows={4}
                              placeholder="This invoice is generated by system with current date and time: {{dateTime}}. No refund available on any service, product, or e-wallet transaction."
                            />
                            <p className="text-xs text-gray-500">
                              Use {'{{dateTime}}'} to auto insert current date and time on invoice generation.
                            </p>
                          </div>

                          <div className="space-y-2">
                            <Label htmlFor="taxRate">Tax Rate (%)</Label>
                            <Input
                              id="taxRate"
                              type="number"
                              step="0.01"
                              value={settings.taxRate}
                              onChange={(e) => handleInputChange('taxRate', parseFloat(e.target.value))}
                            />
                          </div>

                          <Separator />

                          <div className="space-y-4">
                            <h3 className="text-lg font-medium">Payment Method Availability</h3>
                            <div className="space-y-3">
                              <div className="flex items-center justify-between">
                                <div className="space-y-0.5">
                                  <Label>Accept Cash</Label>
                                  <p className="text-sm text-gray-600">Enable cash payments in booking and invoice flows</p>
                                </div>
                                <Switch
                                  checked={settings.acceptCash}
                                  onCheckedChange={(checked) => handleInputChange('acceptCash', checked)}
                                />
                              </div>

                              <div className="flex items-center justify-between">
                                <div className="space-y-0.5">
                                  <Label>Accept Card</Label>
                                  <p className="text-sm text-gray-600">Enable card payments in booking and invoice flows</p>
                                </div>
                                <Switch
                                  checked={settings.acceptCard}
                                  onCheckedChange={(checked) => handleInputChange('acceptCard', checked)}
                                />
                              </div>

                              <div className="flex items-center justify-between">
                                <div className="space-y-0.5">
                                  <Label>Accept Check</Label>
                                  <p className="text-sm text-gray-600">Enable check payments in booking and invoice flows</p>
                                </div>
                                <Switch
                                  checked={settings.acceptCheck}
                                  onCheckedChange={(checked) => handleInputChange('acceptCheck', checked)}
                                />
                              </div>

                              <div className="flex items-center justify-between">
                                <div className="space-y-0.5">
                                  <Label>Accept Digital</Label>
                                  <p className="text-sm text-gray-600">Enable digital payment methods</p>
                                </div>
                                <Switch
                                  checked={settings.acceptDigital}
                                  onCheckedChange={(checked) => handleInputChange('acceptDigital', checked)}
                                />
                              </div>

                              <div className="flex items-center justify-between">
                                <div className="space-y-0.5">
                                  <Label>Accept E-Wallet</Label>
                                  <p className="text-sm text-gray-600">Enable customer e-wallet balance usage</p>
                                </div>
                                <Switch
                                  checked={settings.acceptEwallet}
                                  onCheckedChange={(checked) => handleInputChange('acceptEwallet', checked)}
                                />
                              </div>
                            </div>
                          </div>

                          <Separator />

                          <div className="space-y-4">
                            <h3 className="text-lg font-medium">Card Gateway Integration</h3>

                            <div className="space-y-2">
                              <Label htmlFor="superGatewayProvider">Gateway Provider</Label>
                              <Select
                                value={settings.paymentGateway.provider}
                                onValueChange={(value: 'none' | 'totalpay') =>
                                  setSettings((prev) => ({
                                    ...prev,
                                    paymentGateway: {
                                      ...prev.paymentGateway,
                                      provider: value,
                                    },
                                  }))
                                }
                              >
                                <SelectTrigger id="superGatewayProvider">
                                  <SelectValue />
                                </SelectTrigger>
                                <SelectContent>
                                  <SelectItem value="none">No Card Gateway</SelectItem>
                                  <SelectItem value="totalpay">TotalPay</SelectItem>
                                </SelectContent>
                              </Select>
                            </div>

                            {settings.paymentGateway.provider === 'totalpay' && (
                              <>
                                <div className="flex items-center justify-between">
                                  <div className="space-y-0.5">
                                    <Label>Enable TotalPay</Label>
                                    <p className="text-sm text-gray-600">Allow card payments with TotalPay hosted checkout.</p>
                                  </div>
                                  <Switch
                                    checked={settings.paymentGateway.totalPay.enabled}
                                    onCheckedChange={(checked) => handlePaymentGatewayChange('enabled', checked)}
                                  />
                                </div>

                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                  <div className="space-y-2">
                                    <Label htmlFor="superTotalPayBaseUrl">TotalPay Base URL</Label>
                                    <Input
                                      id="superTotalPayBaseUrl"
                                      placeholder="https://api.totalpay.example"
                                      value={settings.paymentGateway.totalPay.baseUrl}
                                      onChange={(e) => handlePaymentGatewayChange('baseUrl', e.target.value)}
                                    />
                                  </div>

                                  <div className="space-y-2">
                                    <Label htmlFor="superTotalPayCreateInvoiceEndpoint">Create Invoice Endpoint</Label>
                                    <Input
                                      id="superTotalPayCreateInvoiceEndpoint"
                                      placeholder="/invoices"
                                      value={settings.paymentGateway.totalPay.createInvoiceEndpoint}
                                      onChange={(e) => handlePaymentGatewayChange('createInvoiceEndpoint', e.target.value)}
                                    />
                                  </div>

                                  <div className="space-y-2">
                                    <Label htmlFor="superTotalPayMerchantId">Merchant ID</Label>
                                    <Input
                                      id="superTotalPayMerchantId"
                                      value={settings.paymentGateway.totalPay.merchantId}
                                      onChange={(e) => handlePaymentGatewayChange('merchantId', e.target.value)}
                                    />
                                  </div>

                                  <div className="space-y-2">
                                    <Label htmlFor="superTotalPayApiKey">API Key</Label>
                                    <Input
                                      id="superTotalPayApiKey"
                                      value={settings.paymentGateway.totalPay.apiKey}
                                      onChange={(e) => handlePaymentGatewayChange('apiKey', e.target.value)}
                                    />
                                  </div>

                                  <div className="space-y-2">
                                    <Label htmlFor="superTotalPayApiSecret">API Secret</Label>
                                    <Input
                                      id="superTotalPayApiSecret"
                                      type="password"
                                      value={settings.paymentGateway.totalPay.apiSecret}
                                      onChange={(e) => handlePaymentGatewayChange('apiSecret', e.target.value)}
                                    />
                                  </div>

                                  <div className="space-y-2">
                                    <Label htmlFor="superTotalPaySuccessUrl">Success Return URL (Optional)</Label>
                                    <Input
                                      id="superTotalPaySuccessUrl"
                                      placeholder="https://your-domain.com/checkout?payment=success"
                                      value={settings.paymentGateway.totalPay.successUrl}
                                      onChange={(e) => handlePaymentGatewayChange('successUrl', e.target.value)}
                                    />
                                  </div>

                                  <div className="space-y-2">
                                    <Label htmlFor="superTotalPayCancelUrl">Cancel Return URL (Optional)</Label>
                                    <Input
                                      id="superTotalPayCancelUrl"
                                      placeholder="https://your-domain.com/checkout?payment=cancel"
                                      value={settings.paymentGateway.totalPay.cancelUrl}
                                      onChange={(e) => handlePaymentGatewayChange('cancelUrl', e.target.value)}
                                    />
                                  </div>

                                  <div className="space-y-2">
                                    <Label htmlFor="superTotalPayWebhookUrl">Webhook URL (Optional)</Label>
                                    <Input
                                      id="superTotalPayWebhookUrl"
                                      placeholder="https://your-domain.com/api/payments/webhook"
                                      value={settings.paymentGateway.totalPay.webhookUrl}
                                      onChange={(e) => handlePaymentGatewayChange('webhookUrl', e.target.value)}
                                    />
                                  </div>
                                </div>
                              </>
                            )}
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  </TabsContent>

                </Tabs>
              )}
            </div>
          </div>
        </div>
      </div>
    </ProtectedRoute>
  );
}